### ISSUE TITLE
use nbgitpuller in for binderhub links

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/jupyterbook-template#1]
if we can use nbgitpuller in the binderhub launch buttons then it will be easier to ensure people have same environment whether content is launched via binderhub or jupyterhub. 

I naively tried this https://github.com/uwhackweek/jupyterbook-template/blob/b8c6246a1957cf6fb50fd82e27033c304ab0e2c4/book/_config.yml#L28 but think we'll need some upstream changes  https://github.com/executablebooks/jupyter-book/issues/1235

**Comment by jomey** [comment]
We have removed the use of BinderHub with #150
