### ISSUE TITLE
Update placeholder email

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/jupyterbook-template#130]
We have this in the book myst substitutions
https://github.com/uwhackweek/jupyterbook-template/blob/fa80f4c297dce569b6b7f200ab280fe689b86055/book/_config.yml#L21

But `uwhackweek@uw.edu` left over from past events (I think no longer monitored?)
https://github.com/uwhackweek/jupyterbook-template/blob/fa80f4c297dce569b6b7f200ab280fe689b86055/book/logistics.md?plain=1#L14 

@aaarendt @jomey I believe we want to stick with `escience-hackweeks@uw.edu` going forward?

**Comment by jomey** [comment]
That is my suggestion as well. Think for the book, we could also use something more obvious as a placeholder. Maybe something "CONTACT_EMAIL_REPLACEMENT"

**Comment by aaarendt** [comment]
@scottyhq the uwhackweek@uw.edu email no longer exists. escience-hackweeks@uw.edu should be monitored going forward.

But I agree with @jomey 's suggestion to make it generic.
