### ISSUE TITLE
Simplify setupconda action

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/jupyterbook-template#135]
The caching setup here is pretty complicated
https://github.com/uwhackweek/jupyterbook-template/blob/main/.github/actions/setupconda/action.yaml

I think a better strategy would be to change this workflow to use https://github.com/mamba-org/setup-micromamba, which handles conda-lock.yml files cc @jomey

**Comment by jomey** [comment]
I am big fan of `micromamba` ❤️
