### ISSUE TITLE
macos-latest runners now ARM instead of Intel

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/jupyterbook-template#166]
Not sure when this changed, but any use of `macos-latest` on github actions is using [macOS-14-arm64](https://github.com/actions/runner-images/blob/main/images/macos/macos-14-arm64-Readme.md)

which means we need to update conda-lock to also solve the environment for ARM!

https://github.com/uwhackweek/jupyterbook-template/blob/ad103fd42c0173dd5567bb3e0a806f3ea5bf06ee/conda/environment.yml#L27-L29

(noticed in #164)

**Comment by jomey** [comment]
We did this for IceSat-2 already, but never transferred it
https://github.com/ICESAT-2HackWeek/ICESat-2-Hackweek-2023/blob/main/conda/environment.yml
