### ISSUE TITLE
using this template for icesat2 hackweek 2022

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/jupyterbook-template#19]
Planning to use this template for a jupyerbook website for icesat2 hackweek in 2022, but we'll want to tackle a few things first  cc @JessicaS11 @aaarendt 

- [x] wrap up https://github.com/uwhackweek/jupyterbook-template/pull/16 
- [x] bump jupyterbook to latest version. mainly for table of contents improvements, also waiting on support for new google analytics ids, which should be fixed soon https://github.com/executablebooks/jupyter-book/issues/1300#issuecomment-926750758 
- [x] test setup with `fake-IS2/jupyterbook` (temporary fake organization to try things out)

**Comment by JessicaS11** [comment]
See #25 and #28 for the second to-do item

**Comment by JessicaS11** [comment]
@scottyhq Think we're ready for a test setup, or should we wait to close a few more issues? Do you have a temp/fake organization already, or do we need to create one?

**Comment by scottyhq** [comment]
The one other piece that would be especially nice is a rename script (https://github.com/uwhackweek/jupyterbook-template/issues/20), but feel free to create a test organization and repo to see how it goes!

**Comment by JessicaS11** [comment]
I used the ICESat-2HackWeek organization to create a [test](https://github.com/ICESAT-2HackWeek/test_hw_book) with this template (note it's a private repo). I'm adding some basic how-to instructions to this repo's readme as I go/learn (#37). @scottyhq What are we looking for (besides a successful creation of a jupyterbook)? Are we trying to fill in variable values or anything?
