### ISSUE TITLE
update descriptions and roles relative to hackweek service website

### ISSUE THREAD

**Issue by JessicaS11** [uwhackweek/jupyterbook-template#21]
There are a number of updates to the descriptions of project and tutorial roles, in light of our [new definitions](https://uwhackweek.github.io/hackweeks-as-a-service/services.html) on the main hackweek service website.

_Originally posted by @aaarendt in https://github.com/uwhackweek/jupyterbook-template/issues/16#issuecomment-930439226_

**Comment by aaarendt** [comment]
Currently underway with #27

**Comment by JessicaS11** [comment]
@aaarendt what's the status of the education team roles?

**Comment by aaarendt** [comment]
@JessicaS11 let's close this issue and I'll open a new one that relates to updating the best practices for tutorial development section. I suggest we do this in parallel with the content that Naomi and Nicoleta are planning to deliver for ICESat-2.

**Comment by scottyhq** [comment]
After #75, the tutorials section is now just examples with the suggested layout for an event. 

All previous content describing *how* to create a tutorial is in the hackweek guidebook: https://uwhackweek.github.io/hackweeks-as-a-service/resources/tutorials.html 

I suggest going forward that any *procedural* content on how to contribute a tutorial is described in [./CONTRIBUTING.md]( ./CONTRIBUTING.md)
