### ISSUE TITLE
Restore event countdown

### ISSUE THREAD

**Issue by jomey** [uwhackweek/jupyterbook-template#50]
The original template had a countdown to the event:
https://themes.3rdwavemedia.com/demo/bs5/devconf/

Let's restore that!

**Comment by scottyhq** [comment]
Just noticed that it seems the countdown shows up on Chrome but not Safari: 

<img width="1209" alt="Screenshot 2023-07-24 at 8 45 31 PM" src="https://github.com/uwhackweek/jupyterbook-template/assets/3924836/eba28b7e-65d9-42b9-b3dd-3e99df41d10e">

**Comment by jomey** [comment]
> Just noticed that it seems the countdown shows up on Chrome but not Safari:
> 

Do you have an error message for this in your Safari Web Inspector Console?
(Right click anywhere on the page -> Inspector -> Console tab)

**Comment by scottyhq** [comment]
> Do you have an error message for this in your Safari Web Inspector Console? 

`Failed to load resource: the server responded with a status of 404 ()  https://icesat-2-2023.hackweek.io/assets/plugins/bootstrap/js/bootstrap.min.js.map`

**Comment by jomey** [comment]
Let's close this issue once I transfer the ICESat-2 changes over
