### ISSUE TITLE
Links in conda folder not cooperating with git

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/jupyterbook-template#52]
On current main branch I'm seeing:

```
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	typechange: conda-Linux-64.lock

no changes added to commit (use "git add" and/or "git commit -a")
```

But neither adding or removing that file seems to have any affect. I always have `typechange: conda-Linux-64.lock`. Looked into this briefly, but not sure what's going on,,, maybe something with `.zsh` in a mac terminal. @jomey can we just remove these files? I think they were for testing based on this comment https://github.com/uwhackweek/jupyterbook-template/blob/89841735ddcd32385bf017a0b18ef85b54a1be2c/conda/lock-environment.sh#L28

**Comment by scottyhq** [comment]
I believe this is do to the Mac OSX file system not being case sensitive, so `ln -s conda-linux-64.lock conda-Linux-64.lock` ends up effectively being a circular reference

**Comment by jomey** [comment]
You will need those files in order for the GH action to pick the correct lock files based of `os.runner`

**Comment by jomey** [comment]
The above comment can be improved:
```
 # The symbolic link is needed to pick the correct platform lock files using GitHub actions.
```

**Comment by jomey** [comment]
https://stackoverflow.com/questions/52369109/git-core-ignorecase-false-in-mac-os-x

**Comment by scottyhq** [comment]
Thanks for the link. I think we should put logic in the workflow to select the correct file instead of the link because no matter what I seem to set in git configuration I can't get seem to checkout other branches unless I add commits (see below). 'stash' and 'restore' aren't having an effect. 

```
error: Your local changes to the following files would be overwritten by checkout:
	conda/conda-linux-64.lock
Please commit your changes or stash them before you switch branches.
Aborting
```
