### ISSUE TITLE
Add Joe to README contributors

### ISSUE THREAD

**Issue by lsetiawan** [uwhackweek/jupyterbook-template#55]
@jomey is missing from the contributors README. This needs to change 😄  https://github.com/uwhackweek/jupyterbook-template#contributors-

**Comment by scottyhq** [comment]
@all-contributors add @jomey for code, ideas, content

**Comment by lsetiawan** [comment]
You're too fast! 😆 Thanks @scottyhq

**Comment by jomey** [comment]
Pretty slick bot. Thanks guys!
