### ISSUE TITLE
improve docs for how to use this template

### ISSUE THREAD

**Issue by JessicaS11** [uwhackweek/jupyterbook-template#60]
For those not familiar with the repo, it would be great to have a set of instructions that tell how to use it and which files they need to target editing for customization. This was started in #37, prior to a number of action updates and the addition of the splash page.

**Comment by JessicaS11** [comment]
@scottyhq If it helps I've got a `README_jupyterbook.md` file started locally that includes a yaml template for adding new team members

**Comment by scottyhq** [comment]
closed by #67
