### ISSUE TITLE
Upgrade to conda-lock 1.0

### ISSUE THREAD

**Issue by JessicaS11** [uwhackweek/jupyterbook-template#61]
Per the [discussion](https://github.com/uwhackweek/jupyterbook-template/pull/41#discussion_r781567329) in #41, conda and pip don't play well together in conda-lock. This will change with conda-lock 0.13.3, at which point we can simply have
```
- pip:
    - jinja_markdown
 ```

 in `conda/environment.yml`.

Until then, we've added  `jinja2>=2.11`, `pygments>=2.6.1`, `pymdown-extensions >= 7.1` to `environment.yml` and a step to set the shell and run `pip install --no-deps jinja-markdown==1.210911` to the `setupconda/action.yaml`.

**Comment by scottyhq** [comment]
Now that 1.0 is out we should definitely use it! https://github.com/conda-incubator/conda-lock/releases/tag/v1.0.1

**Comment by scottyhq** [comment]
closed by #97
