### ISSUE TITLE
auto-update preview

### ISSUE THREAD

**Issue by JessicaS11** [uwhackweek/jupyterbook-template#65]
In #64, I had to remove and re-add the preview label to regenerate the netlify preview after pushing additional changes to the branch. @scottyhq @jomey, is that the intended behavior?

**Comment by jomey** [comment]
I say 'No'

Should probably look into updating the action, remove the 'types' and change to `pull_request` here:
https://github.com/uwhackweek/jupyterbook-template/blob/1e1936d9379dbee42f5aa472ff99023d4e0e7da4/.github/workflows/netlifypreview.yaml#L4

Then the if conditions for the step will ensure we only running this when labeled.

**Comment by scottyhq** [comment]
We just need to add 'synchronize' back into types. The workflow does run with `pull_request_target` because it needs access to the netlify secrets.
