### ISSUE TITLE
action to update a repo from this template

### ISSUE THREAD

**Issue by JessicaS11** [uwhackweek/jupyterbook-template#68]
@lsetiawan introduced us to [update template](https://www.npmjs.com/package/update-template) and his [use of it](https://github.com/ooi-data/stream_template/blob/main/.github/workflows/update-template.yaml). This means that we don't need to create a new event repo for recurring events. Relevant to #59.

**Comment by JessicaS11** [comment]
The initial infrastructure for this is set up in #71. However, we'll still need to address how this fits in with recurring events and updates to specific portions of the book, website, and environment.

**Comment by jomey** [comment]
The `binder` directory does not need to be updated. The `environment.yml` located in there is generated from the `scripts/lock_environment.sh` and updated each time packages are added/removed.

**Comment by JessicaS11** [comment]
Given that the notebooks created for each event tend to end up as snapshots of content, the ability to update them from the template is of minimal benefit, so we're not going to pursue setting up the template so that it can be easily updated with an action.
