### ISSUE TITLE
Update contributing guide for pip packages

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/jupyterbook-template#82]
Currently, if installing from a lockfile as suggested in the contributing guide **does not**  install `pip` packages.

https://github.com/uwhackweek/jupyterbook-template/blob/9ff908c848e71e1ec4d0c37f768e26e772d3bcdb/CONTRIBUTING.md?plain=1#L33-L34

Similarly, the conda-lock produced [binder/environment.yml](binder/environment.yml) does not include pip packages.

Future versions of conda-lock (#61) can handle both conda and pip (but does not mutually resolve dependencies). The easiest short term solution I think is to include `requirements.txt` as well (with jinja_markdown).

Also, we'll have to instruct tutorial developers using pip packages to install them in the first cell of a notebook (`!pip install mypackage`)

**Comment by JessicaS11** [comment]
Is this resolved now that we're using conda-lock >1.0?

**Comment by scottyhq** [comment]
yes! https://conda.github.io/conda-lock/pip/
