### ISSUE TITLE
Remove hard-coding of Docker Image name

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/jupyterbook-template#83]
Currently `uwhackweek/template` is hardcoded, so if this workflow runs in another repository with permissions, it will push new images instead of a user-defined name (like uwhackweek/icesat2-2022)

https://github.com/uwhackweek/jupyterbook-template/search?q=uwhackweek%2Ftemplate

**Comment by jomey** [comment]
Docker image creation has been remove with #150
