### ISSUE TITLE
Start using forks for pull requests

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/jupyterbook-template#89]
I'm wondering if we should update our contributors guide to encourage using a personal fork for changes. 

The main advantage of this would be when people 'use this template' and 'include all branches' (main + gh_pages), they also get all the development things we are working on here, potentially causing confusion.  @jomey @JessicaS11 thoughts?

**Comment by jomey** [comment]
I am in favor of forks for outside collaborators (not part of the organization).
This is standard practice for any open source project and also an easy entry way for people to contribute.

**Comment by JessicaS11** [comment]
@scottyhq Are you thinking forks for outside collaborators, or all collaborators (including us, within the organization)?

I think ultimately having most or all work done through forks is a reasonable goal. However, particularly in the near-ish term (where it will also most likely be "us" using the template) or for certain dev tasks, I like the ability for us all to work on shared branches. It makes it a lot easier (and faster) to share tasks and fix/finish up PRs and merge them.

**Comment by scottyhq** [comment]
Thanks for the input! Let's keep on with the branching rather than encouraging forks.

> Alternatively, could we just include something in https://github.com/uwhackweek/jupyterbook-template/issues/84 that gets rid of any other branches? 

Great idea! This way we can just use the 'main' branch and then that initial action could create `gh-pages`...

**Comment by scottyhq** [comment]
closing in favor of #84
