### ISSUE TITLE
Rename landing page buttons and branding?

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/jupyterbook-template#90]
In working on the ICESat-2 website I noticed a few things that might be good to modify:

1. Upper left corner title 'Hackweek' --> 'UW eScience Hackweek'?
2. 'Event Details coming Soon' --> Just remove this button? 
3. 'More info' --> Relabel as 'JupyterBook' or 'Event JupyterBook'.. something else? 

thoughts @lsetiawan @JessicaS11 @jomey ?

**Comment by JessicaS11** [comment]
Agreed on all 3 (with a vote for "Event JupyterBook" over "JupyterBook" for # 3).

**Comment by jomey** [comment]
+1 for "Event Jupyter Book" (or JupterBook, whenever we pick one over the other)

I am wondering about the acronym for "UW". It is obvious for US based participants and I am wondering about international folks who are not familiar with US colleges. Too long to write this out?

**Comment by lsetiawan** [comment]
I agree with all 3 also and the "Event Jupyter Book". 

> Too long to write this out?

Spelled out is too long.

**Comment by jomey** [comment]
Attaching another navigation/button experience improvement
https://github.com/ICESAT-2HackWeek/website2022/pull/11/commits/99044aadc2b8dbf8f7e2bef040dec9c36aacfe24

When using a '#' as the href, the homepage will open a new tab each time you click on it. This commit is a small user experience improvement.

**Comment by jomey** [comment]
Logging another small change to the website template for social links:
https://github.com/ICESAT-2HackWeek/website2022/pull/15

The 'if' condition was not correct to only show social links when present on a team member

**Comment by JessicaS11** [comment]
closed by #97
