### ISSUE TITLE
Make schedule tutorial leads links to team section optional

### ISSUE THREAD

**Issue by scottyhq** [uwhackweek/jupyterbook-template#92]
As noted in https://github.com/ICESAT-2HackWeek/website2022/pull/30, there is an error if listing leads on the schedule who are not yet in the team.yaml file. Would be nice if this linking were optional.

Current solution suggested by @jomey  
> instead of having an empty array, just remove the line completely.

 https://github.com/ICESAT-2HackWeek/website2022/blob/a66ad235d220adfd90e5e94e27cb9dc3c0118ad0/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/index.html#L384

**Comment by jomey** [comment]
Another approach is to check for the person existing on line:
https://github.com/ICESAT-2HackWeek/website2022/blob/a66ad235d220adfd90e5e94e27cb9dc3c0118ad0/%7B%7B%20cookiecutter.repo_directory%20%7D%7D/index.html#L389

and adapt the link accordingly

**Comment by JessicaS11** [comment]
closed by #97
